services:
  portfolio:
    build:
      context: .
      dockerfile: artifacts/portfolio/Dockerfile
    container_name: portfolio
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
